spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #    负载均衡配置
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: initialCapacity=500,expireAfterWrite=5s
    #    OSS 对象存储
    alicloud:
      access-key: LTAI5tCcJoXN5npuRvAfneNA
      secret-key: 8Bzkd1jAlL0Jp3jDzePFoicGgqDsax
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: amall-acme
  application:
    name: amall-third-party
server:
  port: 30000
